"""
Initial migration for the profiles application.

This migration creates the Profile model with its fields
and relationship to the Django User model.
"""

# Generated by Django 3.0 on 2025-12-18 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Initial database migration for the profiles application.

    Creates the Profile table with all required fields and
    the one-to-one relationship to the User model.
    """

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_city', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
